### ISSUE TITLE
File size does not increase after 4 kb and ui freezes with full green download bar after pressing download

### ISSUE THREAD

**Issue by Dudamax** [Reisyukaku/CDNX#4] opened 2018-05-17 20:16 UTC

**Comment by Reisyukaku** [comment] 2018-05-17 21:17
Which title? More details please.

**Comment by Dudamax** [comment] 2018-05-18 10:46
So that means the freeze is ok right? And the 4 kb file will get bigger over time?

**Comment by Reisyukaku** [comment] 2018-05-18 21:07
no, the meta and nca are seperate files.. just let it run for a while..

**Comment by Reisyukaku** [comment] 2018-05-20 13:50
Should have been fixed in the last two commits (hopefully).

**Closed by Reisyukaku** 2018-05-20 13:50 UTC

**Comment by GhostlyCrowd** [comment] 2018-05-22 17:48
Just bumping this, even though its closed i';m experiencing this issue on the latest release.  

Says Ready! full green bar, no other output with the 4KB meta file only downloaded. I've checked and rechecked cert and everything else is correct in settings.

**Comment by Reisyukaku** [comment] 2018-05-23 03:01
What OS? What title ID? I cant replicate that issue.

**Comment by GhostlyCrowd** [comment] 2018-05-23 13:02
Windows 10 Pro. TID 0100152000022000 is one for example but none have worked so far.

**Comment by bwq** [comment] 2018-07-10 02:55
Root cause is most likely https://github.com/Reisyukaku/CDNX/issues/7. I have the same error when libgcc_s_dw2-1.dll is missing on the system.
